version: '3'
services:
  app:
    build:
      context: ./
    container_name: 'hunken_docker'
    restart: 'always'
    network_mode: host
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
